{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-backup.fullname" . }}-inline
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres-backup.labels" . | nindent 4 }}
stringData:
{{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ tpl $value $ | quote }}
{{- end }}
{{- end }}
